### ISSUE TITLE
Getting subprocess-exited with error 

### ISSUE THREAD

**Issue by manu123416** [Xilinx/Alveo-PYNQ#25]
Hi,
I am trying to install avleo-examples by using the command below:
`pip install pynq-alveo-examples`
I am getting the below error:
```
Collecting pynq-alveo-examples
  Using cached pynq_alveo_examples-1.0.2.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/home/m992c693/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/m992c693/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/m992c693/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynq/__init__.py", line 4, in <module>
          from . import pl_server
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynq/pl_server/__init__.py", line 18, in <module>
          from .embedded_device import EmbeddedDevice
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynq/pl_server/embedded_device.py", line 11, in <module>
          from pynqmetadata.frontends import Metadata
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/__init__.py", line 7, in <module>
          from . import visualisations
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/__init__.py", line 4, in <module>
          from .metadata_vis import MetadataVis
        File "/tmp/pip-build-env-e_mhcmfz/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/metadata_vis.py", line 4, in <module>
          from IPython.display import display, Javascript, HTML
      ModuleNotFoundError: No module named 'IPython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
Not sure how to resolve this error. Need help. Thank you in advance.

**Comment by STFleming** [comment]
Hi @manu123416,

Thanks for reporting this. Can you try the following command and report back if it works or if you see any errors?

```
pip install pynq-alveo-examples --no-build-isolation
```

You'll need to make sure that you have ``pynq``, ``pynqmetadata``, and ``pynqutils`` installed on your system first. You can do this with the following:
```
pip install pynqmetadata
pip install pynqutils
pip install pynq
```

**Comment by manu123416** [comment]
Thank you Sir. When I executed the commands given above there is no error.

**Comment by manu123416** [comment]
Hello Sir,
Just have one more question:
When I run the command `pynq get-notebooks`, not all the notebooks gets downloaded. Just wanted to make sure is I am doing some error:
```
(base) m992c693@alveo:~$ pynq get-notebooks
The following notebooks modules will be delivered:
- 0-welcome-to-pynq (source: pynq_alveo_examples)
- 1-introduction (source: pynq_alveo_examples)
- 2-kernel-optimization (source: pynq_alveo_examples)
- 3-advanced-features (source: pynq_alveo_examples)
- 4-building-and-emulation (source: pynq_alveo_examples)
- data-compression (source: pynq_alveo_examples)
Do you want to proceed? [Y/n] y
Delivering notebooks './pynq-notebooks/0-welcome-to-pynq'...
Folder '0-welcome-to-pynq' will not be created. Notebooks will be delivered directly in parent directory.
Delivering notebooks './pynq-notebooks/1-introduction'...
The notebooks module '1-introduction' could not be delivered. The module has no notebooks, or no valid overlays were found
Delivering notebooks './pynq-notebooks/2-kernel-optimization'...
The notebooks module '2-kernel-optimization' could not be delivered. The module has no notebooks, or no valid overlays were found
Delivering notebooks './pynq-notebooks/3-advanced-features'...
The notebooks module '3-advanced-features' could not be delivered. The module has no notebooks, or no valid overlays were found
Delivering notebooks './pynq-notebooks/4-building-and-emulation'...
Delivering notebooks './pynq-notebooks/data-compression'...
The notebooks module 'data-compression' could not be delivered. The module has no notebooks, or no valid overlays were found
```
Thank you for great help.

**Comment by STFleming** [comment]
Hi @manu123416,

Would you mind trying to run the following command and letting us know what the output is?
```
xbutil examine
```
 
Thanks again for reporting the issue.

All the best,
Shane

**Comment by manu123416** [comment]
Thank you Sir for your response.
On executing xbutil examine,  I got the below output:
(base) m992c693@alveo:~$ xbutil examine
```
System Configuration
  OS Name              : Linux
  Release              : 4.15.0-20-generic
  Version              : #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
  Machine              : x86_64
  CPU Cores            : 32
  Memory               : 257792 MB
  Distribution         : Ubuntu 18.04 LTS
  GLIBC                : 2.27
  Model                : To Be Filled By O.E.M.

XRT
  Version              : 2.13.466
  Branch               : 2022.1
  Hash                 : f5505e402c2ca1ffe45eb6d3a9399b23a0dc8776
  Hash Date            : 2022-04-14 17:45:07
  XOCL                 : 2.13.466, f5505e402c2ca1ffe45eb6d3a9399b23a0dc8776
  XCLMGMT              : 2.13.466, f5505e402c2ca1ffe45eb6d3a9399b23a0dc8776

Devices present
BDF             :  Shell                               Platform UUID                         Device ID       Device Ready*  
[0000:81:00.1]  :  xilinx_u250_gen3x16_xdma_shell_4_1  12C8FAFB-0632-499D-B1C0-C6676271B8A6  user(inst=128)  Yes            

* Devices that are not ready will have reduced functionality when using XRT tools
```
Please review. Thank you for great help.

**Comment by STFleming** [comment]
Thanks for sharing the output.

I'll try and look into this tomorrow. I'm not sure if there has been a change in the Shell name that we might need to investigate, the Shell name looks different to what I was expecting.

**Comment by mariodruiz** [comment]
Hi @manu123416,

The message is clear `The notebooks module 'data-compression' could not be delivered. The module has no notebooks, or no valid overlays were found`. There's no pre build overlay for the platform you have running, so no notebook is delivered. 

If you want to use that notebook, you can copy the notebook from the repo. But, more importantly, you will have to build the overlay yourself.

Mario

**Comment by mariodruiz** [comment]
I am locking this issue, as the original question was answered.
