### ISSUE TITLE
Preparing wheel metadata ... error while installing alveo examples

### ISSUE THREAD

**Issue by Alvir-Islam** [Xilinx/Alveo-PYNQ#26]
Hello, 
I was trying to install pynq on my alveo system. I followed your [documentation](https://pynq.readthedocs.io/en/v2.5.1/getting_started/alveo_getting_started.html) for the installation. However, while I was trying to execute the pynq-alveo-examples command, the following issue came up. 

```
(base) myterminal@alveo:~$ pip install pynq-alveo-examples --no-build-isolation
Collecting pynq-alveo-examples
  Using cached https://files.pythonhosted.org/packages/1b/06/0080a65633dd014a6c5046238e5578d17fbfcac62be151c3aaef2772e47e/pynq_alveo_examples-1.0.2.tar.gz
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/m105n153/anaconda3/bin/python /home/m105n153/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvuveog32
         cwd: /tmp/pip-install-w0wybh1m/pynq-alveo-examples
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 17, in <module>
        from pynq.utils import build_py
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynq/__init__.py", line 4, in <module>
        from . import pl_server
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynq/pl_server/__init__.py", line 18, in <module>
        from .embedded_device import EmbeddedDevice
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynq/pl_server/embedded_device.py", line 11, in <module>
        from pynqmetadata.frontends import Metadata
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynqmetadata/__init__.py", line 5, in <module>
        from .models.bit_field import BitField
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynqmetadata/models/__init__.py", line 4, in <module>
        from .addrmap import AddressMap
      File "/home/m105n153/anaconda3/lib/python3.7/site-packages/pynqmetadata/models/addrmap.py", line 6, in <module>
        from .metadata_object import MetadataObject
      File "<fstring>", line 1
        (self.name=)
                  ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/m105n153/anaconda3/bin/python /home/m105n153/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvuveog32 Check the logs for full command output.
```
Thanks in advance.

**Comment by mariodruiz** [comment]
Hi @Alvir-Islam,

You need at least Python 3.8 to use `pynq` >= 3.0.0, otherwise you will have to install an older `pynq` version

Mario

**Comment by Alvir-Islam** [comment]
This was helpful. I have installed pynq 2.7.0 and it is working now. 
Thank you Mario.
