### ISSUE TITLE
No module named IPython error even though its installed

### ISSUE THREAD

**Issue by BalaDhinesh** [Xilinx/Alveo-PYNQ#27]
I have Alveo U200 connected to my cloud machine. When I run the `pip install pynq-alveo-examples` command, I get the error as shown in the image:

![image](https://user-images.githubusercontent.com/64545984/221493106-74b6a94e-9e02-4109-99cc-304da341bd9d.png)

My machine has IPython already installed, but it still shows the error.
![image](https://user-images.githubusercontent.com/64545984/221492393-51541383-4671-4090-ae4b-f793cd75d514.png)

Versions:
OS: Ubuntu 20.04
PYNQ: 3.0.1
XRT: 2022.2 -  I have sourced XRT

Any help would be appreciated.

**Comment by mariodruiz** [comment]
Hi @BalaDhinesh,

I suggest you use PYNQ for Alveo within a Conda env.
The installation steps are here https://pynq.readthedocs.io/en/latest/getting_started/alveo_getting_started.html#install-conda

Please, next time use the [pynq.io](https://discuss.pynq.io/) forums to request support. 

Mario

**Comment by BalaDhinesh** [comment]
I apologize for not utilizing the appropriate channel for seeking support. Sure, I won't repeat this again. 

I tried with conda env as well. It produces similar error.

```
(base) ubuntu@test-1:~$ pip install pynq-alveo-examples
Collecting pynq-alveo-examples
  Using cached pynq_alveo_examples-1.0.2.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpumwa9ojr
       cwd: /tmp/pip-install-xwcjebpx/pynq-alveo-examples_0bf2b8b014aa4b5893cc74456f656c4a
  Complete output (29 lines):
  Traceback (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 17, in <module>
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynq/__init__.py", line 4, in <module>
      from . import pl_server
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynq/pl_server/__init__.py", line 18, in <module>
      from .embedded_device import EmbeddedDevice
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynq/pl_server/embedded_device.py", line 11, in <module>
      from pynqmetadata.frontends import Metadata
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/__init__.py", line 7, in <module>
      from . import visualisations
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/__init__.py", line 4, in <module>
      from .metadata_vis import MetadataVis
    File "/tmp/pip-build-env-mn1tmbbp/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/metadata_vis.py", line 4, in <module>
      from IPython.display import display, Javascript, HTML
  ModuleNotFoundError: No module named 'IPython'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1b/06/0080a65633dd014a6c5046238e5578d17fbfcac62be151c3aaef2772e47e/pynq_alveo_examples-1.0.2.tar.gz#sha256=c6b5c1502245eff6f33dac3656f47001a9fe77ae252ff36108f1aa3effc6d245 (from https://pypi.org/simple/pynq-alveo-examples/) (requires-python:>=3.5.2). Command errored out with exit status 1: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpumwa9ojr Check the logs for full command output.
  Downloading pynq_alveo_examples-1.0.1.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 14.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpfwngkhv2
       cwd: /tmp/pip-install-xwcjebpx/pynq-alveo-examples_f97043f091754398b979d3982cbf087f
  Complete output (29 lines):
  Traceback (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 17, in <module>
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynq/__init__.py", line 4, in <module>
      from . import pl_server
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynq/pl_server/__init__.py", line 18, in <module>
      from .embedded_device import EmbeddedDevice
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynq/pl_server/embedded_device.py", line 11, in <module>
      from pynqmetadata.frontends import Metadata
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/__init__.py", line 7, in <module>
      from . import visualisations
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/__init__.py", line 4, in <module>
      from .metadata_vis import MetadataVis
    File "/tmp/pip-build-env-t06hp6l1/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/metadata_vis.py", line 4, in <module>
      from IPython.display import display, Javascript, HTML
  ModuleNotFoundError: No module named 'IPython'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3b/db/8c2f769c1d3f8644ccb46a5c99a563456e36262e1d07b220865b24909a74/pynq_alveo_examples-1.0.1.tar.gz#sha256=8bd7faca978167d0f738773cf0188b36c915597a50625c51c7bbb519b993813f (from https://pypi.org/simple/pynq-alveo-examples/) (requires-python:>=3.5.2). Command errored out with exit status 1: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpfwngkhv2 Check the logs for full command output.
  Downloading pynq_alveo_examples-1.0.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 59.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpx32zjw60
       cwd: /tmp/pip-install-xwcjebpx/pynq-alveo-examples_2a8883d794f4433f84e13581b7b08e90
  Complete output (29 lines):
  Traceback (most recent call last):
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 17, in <module>
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynq/__init__.py", line 4, in <module>
      from . import pl_server
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynq/pl_server/__init__.py", line 18, in <module>
      from .embedded_device import EmbeddedDevice
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynq/pl_server/embedded_device.py", line 11, in <module>
      from pynqmetadata.frontends import Metadata
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/__init__.py", line 7, in <module>
      from . import visualisations
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/__init__.py", line 4, in <module>
      from .metadata_vis import MetadataVis
    File "/tmp/pip-build-env-5xkeywp5/overlay/lib/python3.9/site-packages/pynqmetadata/frontends/visualisations/metadata_vis.py", line 4, in <module>
      from IPython.display import display, Javascript, HTML
  ModuleNotFoundError: No module named 'IPython'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/77/07/d5d82c8076cb78a6ebfefdae1e14f6cb7856ebb73025ef595d80e8046246/pynq_alveo_examples-1.0.tar.gz#sha256=47b7ab73a27c7a11b330c9991218bef203890f4e7cafc4872fd5c46a29f6dfb6 (from https://pypi.org/simple/pynq-alveo-examples/) (requires-python:>=3.5.2). Command errored out with exit status 1: /home/ubuntu/anaconda3/bin/python /home/ubuntu/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpx32zjw60 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pynq-alveo-examples (from versions: 1.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for pynq-alveo-examples

```

I followed the instructions mentioned in the above link for anaconda installation.

**Comment by BalaDhinesh** [comment]
That works. Thanks a lot, @mariodruiz!

**Comment by mariodruiz** [comment]
which one?

**Comment by BalaDhinesh** [comment]
`pip install pynq-alveo-examples --no-build-isolation` works
